name: country_list_pick
description: Flutter plugin project to pick country code, will show code country, dial code, flag country, and name country.
version: 1.0.1+6
repository: https://github.com/holybricks/country-list-pick.git

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  modal_bottom_sheet: ^3.0.0-pre
  figma_squircle: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - flags/
